=== dviorel/iquattrojava101/ValidacionXMLSchema/SchemaPrueba.xsd
<?xml version = "1.0"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.impuestos.gob.bo"
           xmlns="http://www.impuestos.gob.bo" elementFormDefault="qualified">
    <xs:element name = 'class'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name = 'student' type = 'StudentType' minOccurs = '0' maxOccurs = 'unbounded' />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name = "StudentType">
        <xs:sequence>
            <xs:element name = "id" type = "xs:positiveInteger"/>
            <xs:element name = "name" type = "xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== dviorel/iquattrojava101/ValidacionXMLSchema/XMLPrueba.xml
<?xml version = "1.0"?>
<class xmlns = "http://www.impuestos.gob.bo"
       xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation = "http://www.impuestos.gob.bo  SchemaPrueba.xsd">
    <student>
        <ids>85</ids>
        <name>Dinkar</name>
    </student>
    <student>
        <id>86</id>
        <name>Daniel</name>
    </student>
    <student>
        <id>87</id>
        <name>Javier</name>
    </student>
</class>
